name: learn-actions
on: [push]
jobs:
  echo-name:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        run: echo 'rss-fetcher'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::022586301226:role/Github-Role-rss-fetcher-Role-LYBOOIPP4JL1
          aws-region: eu-central-1