name: learn-actions
on: [push]
jobs:
  echo-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      - run: echo 'rss-fetcher'